# Generated by Django 5.2.17 on 2026-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], default='fisico', max_length=7),
        ),
    ]
