# Generated by Django 5.2.17 on 2026-09-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_livro_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 – Generalidades e Informação'), ('100', '100 – Filosofia e Psicologia'), ('200', '200 – Religião e Teologia'), ('300', '300 – Ciências Sociais e Direito'), ('400', '400 – Linguística e Idiomas'), ('500', '500 – Ciências Puras (Exatas e Naturais)'), ('600', '600 – Ciências Aplicadas (Tecnologia)'), ('700', '700 – Artes e Recreação'), ('800', '800 – Literatura'), ('900', '900 – História e Geografia')], default='800', max_length=3),
            preserve_default=False,
        ),
    ]
